// Code generated by oapi-codegen. DO NOT EDIT.
// Package server provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"github.com/getkin/kin-openapi/openapi3"
	"strings"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RYT2/7Ngz9Kga3wwY4dbpdBg87bFgQFCvWoisGDEUPqk2n6mxJleSiQeDvPkh24n9y",
	"2rqJlx9+t1gmqccnPorxBiKeCc6QaQXhBgSRJEON0j5pIleoza+IM43M/tT4qgOREsp+9qJHIhXqX3Kd",
	"zH4yL1X0iBmxZmuBEILSkrIVFEXhQ4wqklRoyhmEVXDvuxhfaIQeZR5nXM0izhK6+h58wFeSidQEoUyj",
	"ZCQFH6hxFUQ/gg+MZLgLBD5IfM6pxBhCLXM0O5ZwbC43DyT6+3w+L63Nk81XcoFSU7Q2l1Tpvt1S8lyY",
	"11RjZu2+lZhACN8ENXlBtVUw5F/4oKm26VxozIbM/C1xREqyNl5uUDfchBqNybq/CcladRE1vByc7qz5",
	"wxNG2uyxh9F30//JdOsYDfRvbdc/ilYBb3aBmst+t/B9WJmING56bJd61sX7+dtS0uZwHETJU2wjrFZG",
	"AnRjc9tdo8yoUhXgj5dxw3/0ER0j/3ZebSZSJMkspUrPGM9Zq7C3AOwLB9Tt+06IfrGa/UiXh3rRFdou",
	"1Mb22cnAoP47iffIMt6UJby5jfFr9n4v4zGmnkjzFTUhXlCWLML52fxsXuXGiKAQwo92ybdXguUvkA8k",
	"Cl6sabApkRV2sZRHitomuWPiIoYQfrfrzn4mUQnO1FZeCclT3VMaWF5UnmVErk28xeXiduEtkZldMPYS",
	"yTPvn1//XJbZ2b5QXq1tIEvUb6P4YT7vXMpEiJRGNkzwpMozr+/ij4nKdVkvF7fe1R+e2bidqHkxTPke",
	"AnzQZKUgvOtUEdwXfmsMuXPjr02CyrG490Fw5SD1mqshVp9zVPo3Hq8nJrRc753reb+yIomGwA7v11d/",
	"3e4rr8Lfo4TA3j/BprqGijHK2I4rJyAPJ5TjaqSa6Q4mlPJERsjF1pFDMkcY2P/FtZdw6a0quh2jeD3X",
	"dGZx/1girs9+CiUPHntrzj8JTQdmggk25RwzXuHVJHwqKnfBmUDp5V+HA6vdntBIyZe19kXo/oiIZFkN",
	"DkC78X3SPrSrzsl60VBh9v70/j896dM96HTaz/Sd59BN5xPtZuJOc0K6nlTS+9R8QkIOROvTxhhNt74R",
	"nIi6hzEdX+fNj1iHVbzr1EZ2AVuCX3Un6JTIVD1hf3W4P4QerU8UxX8BAAD//7KCEKc1GgAA",
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file.
func GetSwagger() (*openapi3.Swagger, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}
