// Code generated by oapi-codegen. DO NOT EDIT.
// Package server provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"github.com/getkin/kin-openapi/openapi3"
	"strings"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYTW/jNhD9KwLbQwtIoZICi1ZFgaZZxwiaxqmTS7EIAkYa2dyVSJakkjUM/feC1Les",
	"eG2vXQdFb/aQmjczfG801BKFPBWcAdMKBUskiCQpaJD2nyZyBtr8CjnTwOxPDZ81Fgmh7GcnnBOpQP+S",
	"6dj70SyqcA4psdsWAlCAlJaUzVCe5y6KQIWSCk05Q0Hp3PkugmcagkOZwxlXXshZTGffIxfBZ5KKxDih",
	"TINkJEEuouZRQfQcuYiRFGpHyEUS/s6ohAgFWmZgEI0FlP6NRxRsRtPasHicPpGwlxsRIqEhMRHij8qE",
	"2U7pWwkxCtA3uKkZLlYVts5ym2Yf43EseSb2ilS6XIf3OOWmdnsHLfy+grx/zC+hPd6CTKlStPC8X+C2",
	"87wIotxjuVTyR0guQOqSYfVhUw2p2uYwXaSptny/0pC2VtxKTERKsjAbqzpvjlHUcQDCLvQRWhttlvU6",
	"f/oIobYhdJjdrcH24bWp1cIeiq3XR5b17rbZ7fcfF80MBI3aT1Smld352oRrmnez3i0syRPoRlVaNg9q",
	"OJyuMLbnu3vchHrC7uaWAIm9hCrtMZ6xDtUqULswEF613nOxyjKDR6rcgWUpCj6g8+tr5KKL6ej8foRc",
	"NB2dv0cPjdPmmSFka2h8XUxuLq/GyEXj6e1F24vdOFitliZXirRSTPMEZTGv+iIJbV+ElNDEvlRj/isX",
	"wBjoFy4/UTY74XLWvFcnAphzUy86lzxjUZVdJo2PudZCBRgPuMldlNAQmLI5ly6vC8sUYm9yc+n9AekT",
	"SO/0xN/AI34RXtnecSYSTiKFz/wzH/vvcMvZhCUL747H+oVI8EpA7/n0xD8RUWzPAWSqJvEdSDN47IB5",
	"+hP2zyxm4Z6ymUdY5F3dTr3L8z89E5Xnv7N43UNrjzhOyiNIHJFkM2oq+gyyIDsysfolBRkRFAXoB2ty",
	"7eRjaY7lEwmxTcvHy2IEyq2xaEUJaFv4mpFXEQrQe2svW7oEJThTVfOKSZbolT6GLPFUlqZELoyH0fXo",
	"fuSMgRm/EDmx5Knz1/nNuMjHdtpiZuxCj0EP4Z75/t5nsP6kOR7dO5PfHQPVTcYs2JqtycdFmsyU0St6",
	"yN3OgPxhOJxmCy5H0/zBRYKrgarcctWUpR5vXku0M87ilVk2X6nt6ep5hhJMnr1K3E7u7tcdau6uYRy2",
	"71G8LF+n+WYMrGabo9BwEHzfXGym9O0ZWdR0I162oHZnqHuQO94nWDgNLQZvb80M1ru+fVEzzRl+pXCa",
	"AfxNyAebeQkvi6lpGzGV4/LxBDUUwGFEVd8Ld1VWr9xbCq2A/y+p7YARVUQeDKi+G+yk/ppwe+kA9f3z",
	"OG1gB9kfU/H/iti/QubbyfrtCvow8tmbct6QZrDofDLYTD6dG/TRhPR6FAeRVO/D5o7qGir8/4pbp7je",
	"Me9De71vdgeTodkN8rk6peZrTYAxAT0H6UkeekRQ1C/qNQ9J4pAwBKUcwSkzN+L8nwAAAP//4eu8D3sa",
	"AAA=",
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file.
func GetSwagger() (*openapi3.Swagger, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}
