// Code generated by oapi-codegen. DO NOT EDIT.
// Package aether_1_0_0 provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package aether_1_0_0

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"github.com/getkin/kin-openapi/openapi3"
	"strings"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8yaX2/bNhDAv4rB7dGus+ZlyLCHAA2CYsWaIcnDMPSBls8OW4lkSSptEPi7D5T/iJRO",
	"NGXJUp4skXci7+53Z4rUK0lEJgUHbjS5eiU6eYKMFpfXSQJa3ymxYinYBqmEBGUYFN2fmDaeSE2eGcgK",
	"0V8VrMgV+WVejjXfDTQPPGIzJYYZ+yzy0UAWkJwS8yKtHFWKvpCNo9kgKBZfITF2iLANvs1L0Ili0jDB",
	"7e1+DLf5MII2ivG1HWHFUgPKVdi1ILJs6cqxJSazbSilivua3AazVfJwPA/9vmRcJDHlagwxmVD0ECnM",
	"nJBhVPIZp5nnskMb4t7TgrzkeiYVy6h68bSc5gYtDYngS0Sv7EA01z9nwOkiBQ8Yp/WgsxAiBcpj6cpM",
	"boVWQmXUWCluLt+TMiS2/6DGuIE1KJy2f0S4epT9vmQUbahyhTZUJkAbJoWZEzIMk7qW/DpbqFNM2que",
	"zOXxkG8ibXWsqFRF8YOnjH8LYnMQqrMzJbk8qr8Twcmrxa8+a8TI+3xhXbcAhfNZ9j/Gc+kpVXj0+gIc",
	"OhMLTvsR4c/t3bmg1ZwPOpWR7kE9M76+SzPe5nGu2mZKkJIVqldSMaGYeQmScRDCyFLwPQdtYDmj0ksb",
	"vwNJnBz81Cnuo5KnKQRhwvaSpy2jjj8pwCKuUAV0WvxrynJi7p+prCqVjvwuNKblNmPul5iS04qGopZA",
	"TgQiI3VkCUiLbtQNfg9iE01T8cOnf99Up/8YWZWE9GeZJUn4TzxJ0HTJ+BE9jusZGtaz/cHS3WQZ4oRH",
	"GVxVHLo9uagkQlQrWYNIBOo4IoSYEbBnh1QiuFEiRWDb9/S2jI1ZIeYa1EymlPupWbZGVEnbxPhKuE8Q",
	"XBQWrdh6koklpBOZ5mtm5/kMSheGkN/eXby7mAmqL+1UhAROJSNX5NK2kymR1DwVvptTME+g5s+Fxrye",
	"t0tIwRRX1uXUeuTjklyRD0V7tRYq0FJwvX8PXNE8NbVXQlKYqvNs+xpAPtx8unm4mdwCtwPAcrJSIpv8",
	"e/337dbAYiEPpj6HWzDBCby/uLA/NvzAzfYtR6YsKZ4w/6q3Md9y3eoNfBsZ36jbm4fJ578mdsyiL852",
	"qxWMQcAttqCsNbn6j5AvdhkgNOKjO6FNL1G6+3z/EIrRZhqGqXr7ypabloC9LdrGQW8sDk/B0p9rwShV",
	"NAMDyvZ77jHw08xlShn/Y5I8UaXB/Jmb1ex330/Vklkz/xu8TFZCTWrrDGZ7bd0jU7Ld6NgWbrvEZcqu",
	"N4zKYfMlOpHGyip/eXkkfdydoeHTpXH0XtPD2Uc7ZzqUfu+lJneOTCd0vOvIUozvSo5I1dB8DU9aa+qc",
	"KQ5cb73X216KbY+8tc+Vyvt4ODW8LdHBE6J59D7TwN1APiP8jt/7KLPdI9MJHe/apgjd7Q3H8oRt0Y4I",
	"2NHpnIc4ZKd/GATR+EVxiZ6DxLLaW9T7gzdujdBwlvQmiB0a1TEYbYnmwGsEfzO7jzVCn7y1zxXtHY2F",
	"M8M7rRo8H5pH7zMLnFHOyX7p9j5WCN0D0wWceQ5z6Zx+xULkndiMiFPzPM4Dlnv0OghiboCicPMOnmPR",
	"6x7OviCsbdP695vTIB1957b1pM6N73D7uFFxbo32gde3t61bk2mzojgbvV0TVG/Pe2dyd5Qdn4T+SfGo",
	"qReYyrkSzvu2ZrA0c6N1zr+NHmLbFczXHKLeDSvfdY3K4VDwDUdcS8gGLtt5Q6nefS52aoEeDnn/Q6sw",
	"6O4HLYNT3jh4n4g7X/6cke/S532853WOShdo3Mu4nTT0G6rxaBoWq6H5aotaOb+By6jsef+sP8qOZsdm",
	"838AAAD//+felEBGNQAA",
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file.
func GetSwagger() (*openapi3.Swagger, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}
