// Code generated by oapi-codegen. DO NOT EDIT.
// Package types provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package types

import (
	externalRef0 "github.com/onosproject/aether-roc-api/pkg/aether_2_0_0/types"
	externalRef1 "github.com/onosproject/aether-roc-api/pkg/rbac_1_0_0/types"
)

// Elements defines model for Elements.
type Elements struct {
	AccessProfile200       *externalRef0.AccessProfile       `json:"Access-profile-2.0.0,omitempty"`
	ApnProfile200          *externalRef0.ApnProfile          `json:"Apn-profile-2.0.0,omitempty"`
	ConnectivityService200 *externalRef0.ConnectivityService `json:"Connectivity-service-2.0.0,omitempty"`
	Enterprise200          *externalRef0.Enterprise          `json:"Enterprise-2.0.0,omitempty"`
	QosProfile200          *externalRef0.QosProfile          `json:"Qos-profile-2.0.0,omitempty"`
	Rbac100                *externalRef1.Rbac                `json:"Rbac-1.0.0,omitempty"`
	SecurityProfile200     *externalRef0.SecurityProfile     `json:"Security-profile-2.0.0,omitempty"`
	Subscriber200          *externalRef0.Subscriber          `json:"Subscriber-2.0.0,omitempty"`
	UpProfile200           *externalRef0.UpProfile           `json:"Up-profile-2.0.0,omitempty"`
}

// PatchBody defines model for PatchBody.
type PatchBody struct {
	Deletes *Elements `json:"Deletes,omitempty"`

	// Model type and version of 'target' on first creation [link](https://docs.onosproject.org/onos-config/docs/gnmi_extensions/#use-of-extension-101-device-version-in-setrequest)
	Extensions *struct {
		ModelType102    *string `json:"model-type-102,omitempty"`
		ModelVersion101 *string `json:"model-version-101,omitempty"`
	} `json:"Extensions,omitempty"`
	Updates *Elements `json:"Updates,omitempty"`

	// Target (device name) to use by default if not specified on indivdual updates/deletes as an additional property
	DefaultTarget string `json:"default-target"`
}

// TargetName defines model for TargetName.
type TargetName struct {
	Name *string `json:"name,omitempty"`
}

// TargetsNames defines model for TargetsNames.
type TargetsNames []TargetName

// PatchTopLevelJSONBody defines parameters for PatchTopLevel.
type PatchTopLevelJSONBody PatchBody

// PatchTopLevelJSONRequestBody defines body for PatchTopLevel for application/json ContentType.
type PatchTopLevelJSONRequestBody PatchTopLevelJSONBody
