// Code generated by GENERATOR. DO NOT EDIT.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.7.0 DO NOT EDIT.
package types

import (
	externalRef0 "github.com/onosproject/aether-roc-api/pkg/aether_3_0_0/types"
	externalRef1 "github.com/onosproject/aether-roc-api/pkg/aether_4_0_0/types"
)

// Elements defines model for Elements.
type Elements struct {

	// The top level container
	ApList300 *externalRef0.ApList `json:"ap-list-3.0.0,omitempty"`

	// The top level container
	Application300 *externalRef0.Application `json:"application-3.0.0,omitempty"`

	// The top level container
	Application400 *externalRef1.Application `json:"application-4.0.0,omitempty"`

	// The top level container
	ConnectivityService300 *externalRef0.ConnectivityService `json:"connectivity-service-3.0.0,omitempty"`

	// The top level container
	ConnectivityService400 *externalRef1.ConnectivityService `json:"connectivity-service-4.0.0,omitempty"`

	// The top level container
	DeviceGroup300 *externalRef0.DeviceGroup `json:"device-group-3.0.0,omitempty"`

	// The top level container
	DeviceGroup400 *externalRef1.DeviceGroup `json:"device-group-4.0.0,omitempty"`

	// The top level container
	Enterprise300 *externalRef0.Enterprise `json:"enterprise-3.0.0,omitempty"`

	// The top level container
	Enterprise400 *externalRef1.Enterprise `json:"enterprise-4.0.0,omitempty"`

	// The top level container
	IpDomain300 *externalRef0.IpDomain `json:"ip-domain-3.0.0,omitempty"`

	// The top level container
	IpDomain400 *externalRef1.IpDomain `json:"ip-domain-4.0.0,omitempty"`

	// The top level container
	Site300 *externalRef0.Site `json:"site-3.0.0,omitempty"`

	// The top level container
	Site400 *externalRef1.Site `json:"site-4.0.0,omitempty"`

	// The top level container
	Template300 *externalRef0.Template `json:"template-3.0.0,omitempty"`

	// The top level container
	Template400 *externalRef1.Template `json:"template-4.0.0,omitempty"`

	// The top level container
	TrafficClass300 *externalRef0.TrafficClass `json:"traffic-class-3.0.0,omitempty"`

	// The top level container
	TrafficClass400 *externalRef1.TrafficClass `json:"traffic-class-4.0.0,omitempty"`

	// The top level container
	Upf300 *externalRef0.Upf `json:"upf-3.0.0,omitempty"`

	// The top level container
	Upf400 *externalRef1.Upf `json:"upf-4.0.0,omitempty"`

	// The top level container
	Vcs300 *externalRef0.Vcs `json:"vcs-3.0.0,omitempty"`

	// The top level container
	Vcs400 *externalRef1.Vcs `json:"vcs-4.0.0,omitempty"`
}

// PatchBody defines model for PatchBody.
type PatchBody struct {
	Deletes *Elements `json:"Deletes,omitempty"`

	// Model type and version of 'target' on first creation [link](https://docs.onosproject.org/onos-config/docs/gnmi_extensions/#use-of-extension-101-device-version-in-setrequest)
	Extensions *struct {
		ChangeName100   *string `json:"change-name-100,omitempty"`
		ModelType102    *string `json:"model-type-102,omitempty"`
		ModelVersion101 *string `json:"model-version-101,omitempty"`
	} `json:"Extensions,omitempty"`
	Updates *Elements `json:"Updates,omitempty"`

	// Target (device name) to use by default if not specified on indivdual updates/deletes as an additional property
	DefaultTarget string `json:"default-target"`
}

// TargetName defines model for TargetName.
type TargetName struct {
	Name *string `json:"name,omitempty"`
}

// TargetsNames defines model for TargetsNames.
type TargetsNames []TargetName

// PatchTopLevelJSONBody defines parameters for PatchTopLevel.
type PatchTopLevelJSONBody PatchBody

// PatchTopLevelJSONRequestBody defines body for PatchTopLevel for application/json ContentType.
type PatchTopLevelJSONRequestBody PatchTopLevelJSONBody
