# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

components:
  schemas:
    PatchBody:
      properties:
        Updates:
          title: Updated elements
          description: Elements to be updated or replaced
          $ref: '#/components/schemas/Elements'
        Deletes:
          title: Deleted elements
          description: Elements to be deleted
          $ref: '#/components/schemas/Elements'
        Extensions:
          title: gnmi extensions
          description: Model type and version of 'target' on first creation [link](https://docs.onosproject.org/onos-config/docs/gnmi_extensions/#use-of-extension-101-device-version-in-setrequest)
          properties:
            change-name-100:
              type: string
              title: change-name-100
              deprecated: true
            model-version-101:
              type: string
              title: model-version-101
              deprecated: true
            model-type-102:
              type: string
              title: model-type-102
              deprecated: true
            transaction-info-110:
              type: object
              properties:
                id:
                  type: string
                index:
                  type: integer
              title: transaction-info-110
              description: Used in the responses, carries inforamtion about the transaction.
            transaction-strategy-111:
              type: integer
              title: transaction-strategy-111
              description: "Identifies whether a request needs to be handles Asynchronously (val: 0) or Synchronously (val: 1)"
          type: object
        default-target:
          description: Target (device name) to use by default if not specified on indivdual updates/deletes as an additional property
          type: string
          pattern: '[0-9a-z\-\._]+'
      required:
      - default-target
    Elements:
      properties:
        application-4.0.0:
          title: Application 4.0.0 updates
          $ref: './aether-4.0.0-openapi3.yaml#/components/schemas/Application'
        connectivity-service-4.0.0:
          title: Connectivity-service 4.0.0 updates
          $ref: './aether-4.0.0-openapi3.yaml#/components/schemas/Connectivity-service'
        device-group-4.0.0:
          title: Device Group 4.0.0 updates
          $ref: './aether-4.0.0-openapi3.yaml#/components/schemas/Device-group'
        enterprise-4.0.0:
          title: Enterprise 4.0.0 updates
          $ref: './aether-4.0.0-openapi3.yaml#/components/schemas/Enterprise'
        ip-domain-4.0.0:
          title: IP Domain 4.0.0 updates
          $ref: './aether-4.0.0-openapi3.yaml#/components/schemas/Ip-domain'
        site-4.0.0:
          title: Site 4.0.0 updates
          $ref: './aether-4.0.0-openapi3.yaml#/components/schemas/Site'
        template-4.0.0:
          title: Template 4.0.0 updates
          $ref: './aether-4.0.0-openapi3.yaml#/components/schemas/Template'
        traffic-class-4.0.0:
          title: Traffic Class 4.0.0 updates
          $ref: './aether-4.0.0-openapi3.yaml#/components/schemas/Traffic-class'
        upf-4.0.0:
          title: UPF 4.0.0 updates
          $ref: './aether-4.0.0-openapi3.yaml#/components/schemas/Upf'
        vcs-4.0.0:
          title: VCS 4.0.0 updates
          $ref: './aether-4.0.0-openapi3.yaml#/components/schemas/Vcs'
        connectivity-services-2.0.0:
          title: Connectivity-service 2.0.0 updates
          $ref: './aether-2.0.0-openapi3.yaml#/components/schemas/Connectivity-services'
        enterprises-2.0.0:
          title: Enterprise 2.0.0 updates
          $ref: './aether-2.0.0-openapi3.yaml#/components/schemas/Enterprises'
    TargetName:
      properties:
        name:
          type: string
    TargetsNames:
      items:
        $ref: '#/components/schemas/TargetName'
      type: array
    ChangeValue:
      description: an individual Path/Value and removed flag combination in a Change
      properties:
        path:
          description: the path to change
          type: string
        value:
          description: the change value
          type: string
        removed:
          description: indicates whether this is a delete
          type: boolean
      required:
        - path
      type: object
    Change:
      description: represents a configuration change to a single target
      properties:
        target_id:
          description: the identifier of the target to which this change applies
          type: string
        target_version:
          description: an optional target version to which to apply this change
          type: string
        target_type:
          description: an optional target type to which to apply this change
          type: string
        values:
          description: a set of change values to apply
          items:
            $ref: '#/components/schemas/ChangeValue'
          type: array
      required:
        - target_id
      type: object
    Transaction:
      description: Transaction refers to a multi-target transactional change. Taken from https://github.com/onosproject/onos-api/tree/master/proto/onos/config/v2
      properties:
        meta:
          description:
          properties:
            key:
              description:
              type: string
            version:
              description:
              type: integer
              format: uint64
            revision:
              description: the change revision number
              properties:
                revision:
                  description: Revision is a revision number
                  type: integer
                  format: int64
            created:
              description: the time at which the transaction was created
              type: string
              format: date-time
            updated:
              description: the time at which the transaction was last updated
              type: string
              format: date-time
            deleted:
              description: a flag indicating whether this transaction is being deleted by a snapshot
              type: string
              format: date-time
        id:
          description: the unique identifier of the transaction
          type: string
        index:
          description: a monotonically increasing, globally unique index of the change
          type: integer
          format: int64
        username:
          description: the name of the user that made the transaction
          type: string
        strategy:
          description:
          properties:
            synchronicity:
              description: indicates the transaction synchronicity level
              type: string
              enum:
                - ASYNCHRONOUS
                - SYNCHRONOUS
            isolation:
              description: indicates the transaction isolation level
              type: string
              enum:
                - DEFAULT
                - SERIALIZABLE
        details:
          description: the transaction details
          properties:
            change:
              description:
              properties:
                #TODO: ChangeTransaction not implemented as its map
                values:
                  description: a set of changes to apply to targets
            rollback:
              description: rollback
              properties:
                rollback_index:
                  description: the index of the transaction to roll back
                  type: integer
                  format: int64
        status:
          description: the current lifecycle status of the transaction
          properties:
            phases:
              description: the transaction phases
              properties:
                initialize:
                  description: the transaction initialization phase status
                  properties:
                    status:
                      properties:
                        start:
                          type: string
                          format: date-time
                        end:
                          type: string
                          format: date-time
                    state:
                      type: string
                      enum:
                        - INITIALIZING
                        - INITIALIZED
                        - FAILED
                    failure:
                      description: the transaction failure
                      properties:
                        type:
                          description: transaction failure type
                          type: string
                          enum:
                            - UNKNOWN
                            - CANCELED
                            - NOT_FOUND
                            - ALREADY_EXISTS
                            - UNAUTHORIZED
                            - FORBIDDEN
                            - CONFLICT
                            - INVALID
                            - UNAVAILABLE
                            - NOT_SUPPORTED
                            - TIMEOUT
                            - INTERNAL
                        description:
                          type: string
                validate:
                  description: the transaction validation phase status
                  properties:
                    status:
                      properties:
                        start:
                          type: string
                          format: date-time
                        end:
                          type: string
                          format: date-time
                    state:
                      type: string
                      enum:
                        - INITIALIZING
                        - INITIALIZED
                        - FAILED
                    failure:
                      description: the transaction failure
                      properties:
                        type:
                          description: transaction failure type
                          type: string
                          enum:
                            - UNKNOWN
                            - CANCELED
                            - NOT_FOUND
                            - ALREADY_EXISTS
                            - UNAUTHORIZED
                            - FORBIDDEN
                            - CONFLICT
                            - INVALID
                            - UNAVAILABLE
                            - NOT_SUPPORTED
                            - TIMEOUT
                            - INTERNAL
                        description:
                          type: string
                commit:
                  description: the transaction commit phase status
                  properties:
                    status:
                      properties:
                        start:
                          type: string
                          format: date-time
                        end:
                          type: string
                          format: date-time
                    state:
                      type: string
                      enum:
                        - COMMITTING
                        - COMMITTED
                apply:
                  description: the transaction apply phase status
                  properties:
                    status:
                      properties:
                        start:
                          type: string
                          format: date-time
                        end:
                          type: string
                          format: date-time
                    state:
                      type: string
                      enum:
                        - APPLYING
                        - APPLIED
                        - FAILED
                    failure:
                      description: the transaction failure
                      properties:
                        type:
                          description: transaction failure type
                          type: string
                          enum:
                            - UNKNOWN
                            - CANCELED
                            - NOT_FOUND
                            - ALREADY_EXISTS
                            - UNAUTHORIZED
                            - FORBIDDEN
                            - CONFLICT
                            - INVALID
                            - UNAVAILABLE
                            - NOT_SUPPORTED
                            - TIMEOUT
                            - INTERNAL
                        description:
                          type: string
                abort:
                  description:
                  properties:
                    status:
                      properties:
                        start:
                          type: string
                          format: date-time
                        end:
                          type: string
                          format: date-time
                    state:
                      type: string
                      enum:
                        - ABORTING
                        - ABORTED
            proposals:
              description: the set of proposals managed by the transaction
              type: array
            state:
              description: the overall transaction state
              type: string
              enum:
                - PENDING
                - VALIDATED
                - COMMITTED
                - APPLIED
                - FAILED
            failure:
              description: the transaction failure
              properties:
                type:
                  description: transaction failure type
                  type: string
                  enum:
                    - UNKNOWN
                    - CANCELED
                    - NOT_FOUND
                    - ALREADY_EXISTS
                    - UNAUTHORIZED
                    - FORBIDDEN
                    - CONFLICT
                    - INVALID
                    - UNAVAILABLE
                    - NOT_SUPPORTED
                    - TIMEOUT
                    - INTERNAL
                description:
                  type: string
      required:
        - id
        - index
        - meta
    TransactionList:
      items:
        $ref: '#/components/schemas/Transaction'
      type: array
info:
  contact:
    email: info@opennetworking.org
    name: Open Networking Foundation
    url: https://opennetworking.org
  license:
    name: Apache-2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  title: Aether Top Level
  description: |-
    The "Aether Top Level" can be used for the PATCH command.
    It allows several of the Resources of the model specific resources to be committed in one command.
    GETs should continue to be done through the individual REST resources.

    > This interface is intended to be used only by expert users. It is used by the GUI to make multiple
      commits in 1 transaction. e.g. deleting many resources at once.

  version: 2.0.0
openapi: 3.0.0
paths:
  /aether-roc-api:
    patch:
      operationId: patch-top-level
      responses:
        "200":
          description: patched
      summary: PATCH at the top level of aether-roc-api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchBody'
  /targets:
    get:
      operationId: targets-top-level
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TargetsNames'
          description: GET OK 200
      summary: GET /targets A list of just target names
  /sdcore/synchronize/{service}:
    post:
      operationId: sdcore-push-config-top-level
      responses:
        "200":
          description: synchronized
      summary: POST /sdcore/synchronize/{service}
    parameters:
      - content:
          text/plain; charset=utf-8:
            schema:
              type: string
        description: sdcore service name e.g. sdcore-adapter-v4
        in: path
        name: service
        required: true
  /transactions:
    get:
      operationId: get-transactions
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionList'
          description: GET OK 200
      summary: GET /transactions
      tags:
        - TransactionList
  /spec:
    get:
      operationId: spec-top-level
      responses:
        "200":
          content:
            application/yaml:
              schema:
                type: string
          description: GET OK 200
      summary: GET /spec The Top Level Spec in YAML format. Same as aether-top-level-openapi3.yaml
  /spec/aether-2.0.0-openapi3.yaml:
    get:
      operationId: spec-aether-200
      responses:
        "200":
          content:
            application/yaml:
              schema:
                type: string
          description: GET OK 200
      summary: GET /spec/aether-2.0.0-openapi3.yaml The Aether 2.0.0 spec
  /spec/aether-4.0.0-openapi3.yaml:
    get:
      operationId: spec-aether-400
      responses:
        "200":
          content:
            application/yaml:
              schema:
                type: string
          description: GET OK 200
      summary: GET /spec/aether-4.0.0-openapi3.yaml The Aether 4.0.0 spec

