# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-1.0

components:
  schemas:
    PatchBody:
      properties:
        Updates:
          title: Updated elements
          description: Elements to be updated or replaced
          $ref: '#/components/schemas/Elements'
        Deletes:
          title: Deleted elements
          description: Elements to be deleted
          $ref: '#/components/schemas/Elements'
        Extensions:
          title: gnmi extensions
          description: Model type and version of 'target' on first creation [link](https://docs.onosproject.org/onos-config/docs/gnmi_extensions/#use-of-extension-101-device-version-in-setrequest)
          properties:
            change-name-100:
              type: string
              title: change-name-100
            model-version-101:
              type: string
              title: model-version-101
            model-type-102:
              type: string
              title: model-type-102
          type: object
        default-target:
          description: Target (device name) to use by default if not specified on indivdual updates/deletes as an additional property
          type: string
          pattern: '[0-9a-z\-\._]+'
      required:
      - default-target
    Elements:
      properties:
        access-profile-2.0.0:
          title: Access-profile 2.0.0 updates
          $ref: './aether-2.0.0-openapi3.yaml#/components/schemas/Access-profile'
        apn-profile-2.0.0:
          title: Apn-profile 2.0.0 updates
          $ref: './aether-2.0.0-openapi3.yaml#/components/schemas/Apn-profile'
        connectivity-service-2.0.0:
          title: Connectivity-service 2.0.0 updates
          $ref: './aether-2.0.0-openapi3.yaml#/components/schemas/Connectivity-service'
        enterprise-2.0.0:
          title: Enterprise 2.0.0 updates
          $ref: './aether-2.0.0-openapi3.yaml#/components/schemas/Enterprise'
        qos-profile-2.0.0:
          title: Qos-profile 2.0.0 updates
          $ref: './aether-2.0.0-openapi3.yaml#/components/schemas/Qos-profile'
        security-profile-2.0.0:
          title: Security-profile 2.0.0 updates
          $ref: './aether-2.0.0-openapi3.yaml#/components/schemas/Security-profile'
        subscriber-2.0.0:
          title: Subscriber 2.0.0 updates
          $ref: './aether-2.0.0-openapi3.yaml#/components/schemas/Subscriber'
        up-profile-2.0.0:
          title: Up-profile 2.0.0 updates
          $ref: './aether-2.0.0-openapi3.yaml#/components/schemas/Up-profile'
        access-profile-2.1.0:
          title: Access-profile 2.1.0 updates
          $ref: './aether-2.1.0-openapi3.yaml#/components/schemas/Access-profile'
        apn-profile-2.1.0:
          title: Apn-profile 2.1.0 updates
          $ref: './aether-2.1.0-openapi3.yaml#/components/schemas/Apn-profile'
        connectivity-service-2.1.0:
          title: Connectivity-service 2.1.0 updates
          $ref: './aether-2.1.0-openapi3.yaml#/components/schemas/Connectivity-service'
        enterprise-2.1.0:
          title: Enterprise 2.1.0 updates
          $ref: './aether-2.1.0-openapi3.yaml#/components/schemas/Enterprise'
        qos-profile-2.1.0:
          title: Qos-profile 2.1.0 updates
          $ref: './aether-2.1.0-openapi3.yaml#/components/schemas/Qos-profile'
        security-profile-2.1.0:
          title: Security-profile 2.1.0 updates
          $ref: './aether-2.1.0-openapi3.yaml#/components/schemas/Security-profile'
        service-group-2.1.0:
          title: Service-group 2.1.0 updates
          $ref: './aether-2.1.0-openapi3.yaml#/components/schemas/Service-group'
        service-policy-2.1.0:
          title: Service-policy 2.1.0 updates
          $ref: './aether-2.1.0-openapi3.yaml#/components/schemas/Service-policy'
        service-rule-2.1.0:
          title: Service-rule 2.1.0 updates
          $ref: './aether-2.1.0-openapi3.yaml#/components/schemas/Service-rule'
        subscriber-2.1.0:
          title: Subscriber 2.1.0 updates
          $ref: './aether-2.1.0-openapi3.yaml#/components/schemas/Subscriber'
        up-profile-2.1.0:
          title: Up-profile 2.1.0 updates
          $ref: './aether-2.1.0-openapi3.yaml#/components/schemas/Up-profile'
    TargetName:
      properties:
        name:
          type: string
    TargetsNames:
      items:
        $ref: '#/components/schemas/TargetName'
      type: array
info:
  contact:
    email: info@opennetworking.org
    name: Open Networking Foundation
    url: https://opennetworking.org
  license:
    name: LicenseRef-ONF-Member-1.0
    url: https://opennetworking.org/wp-content/uploads/2020/06/ONF-Member-Only-Software-License-v1.0.pdf
  termsOfService: https://opennetworking.org/wp-content/uploads/2019/02/ONF-Licensing-and-IPR-FAQ-2020-06.pdf
  title: Aether Top Level
  version: 2.1.0
openapi: 3.0.0
paths:
  /aether-roc-api:
    patch:
      operationId: patch-top-level
      responses:
        "200":
          description: patched
      summary: PATCH at the top level of aether-roc-api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchBody'
  /targets:
    get:
      operationId: targets-top-level
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TargetsNames'
          description: GET OK 200
      summary: GET /targets A list of just target names
