# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: LicenseRef-ONF-Member-1.0
components:
  parameters:
    target:
      content:
        text/plain; charset=utf-8:
          schema:
            type: string
      description: target (device in onos-config)
      example: internal
      in: path
      name: target
      required: true
  schemas:
    RbacV100targetRbac:
      properties:
        ListRbacV100targetRbacGroup:
          items:
            $ref: '#/components/schemas/RbacV100targetRbacGroup'
          title: ItemRbacV100targetRbacGroup
          type: array
        ListRbacV100targetRbacRole:
          items:
            $ref: '#/components/schemas/RbacV100targetRbacRole'
          title: ItemRbacV100targetRbacRole
          type: array
      title: RbacV100targetRbac
      type: object
    RbacV100targetRbacGroup:
      properties:
        ListRbacV100targetRbacGroupRole:
          items:
            $ref: '#/components/schemas/RbacV100targetRbacGroupRole'
          title: ListRbacV100targetRbacGroupRole
          type: array
        description:
          title: description
          type: string
        groupid:
          title: groupid
          type: string
      type: object
    RbacV100targetRbacGroupRole:
      properties:
        description:
          title: description
          type: string
        roleid:
          title: roleid
          type: string
      type: object
    RbacV100targetRbacRole:
      properties:
        RbacV100targetRbacRolePermission:
          $ref: '#/components/schemas/RbacV100targetRbacRolePermission'
        description:
          title: description
          type: string
        roleid:
          title: roleid
          type: string
      type: object
    RbacV100targetRbacRolePermission:
      properties:
        leaf-list-noun:
          items:
            title: noun
            type: string
          title: leaf-list-noun
          type: array
        operation:
          title: operation
          type: string
        type:
          title: type
          type: string
      title: RbacV100targetRbacRolePermission
      type: object
info:
  title: Rbac onos-config model plugin
  version: 1.0.0
openapi: 3.0.0
paths:
  /rbac/v1.0.0/{target}/rbac:
    delete:
      operationId: deleteRbacV100targetRbac
      responses:
        default:
          description: ""
      summary: DELETE Generated from YANG model
    get:
      operationId: getRbacV100targetRbac
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RbacV100targetRbac'
          description: GET OK 200
      summary: GET /rbac/v1.0.0/{target}/rbac Generated from YANG model
      tags:
      - RbacV100target
    parameters:
    - $ref: '#/components/parameters/target'
    post:
      operationId: postRbacV100targetRbac
      responses:
        default:
          description: ""
      summary: POST Generated from YANG model
  /rbac/v1.0.0/{target}/rbac/group/{groupid}:
    delete:
      operationId: deleteRbacV100targetRbacGroup
      responses:
        default:
          description: ""
      summary: DELETE Generated from YANG model
    get:
      operationId: getRbacV100targetRbacGroup
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RbacV100targetRbacGroup'
          description: GET OK 200
      summary: GET /rbac/v1.0.0/{target}/rbac/group Generated from YANG model
      tags:
      - RbacV100targetRbac
    parameters:
    - content:
        text/plain; charset=utf-8:
          schema:
            type: string
      description: key for group
      in: path
      name: groupid
      required: true
    - $ref: '#/components/parameters/target'
    post:
      operationId: postRbacV100targetRbacGroup
      responses:
        default:
          description: ""
      summary: POST Generated from YANG model
  /rbac/v1.0.0/{target}/rbac/group/role/{roleid}:
    delete:
      operationId: deleteRbacV100targetRbacGroupRole
      responses:
        default:
          description: ""
      summary: DELETE Generated from YANG model
    get:
      operationId: getRbacV100targetRbacGroupRole
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RbacV100targetRbacGroupRole'
          description: GET OK 200
      summary: GET /rbac/v1.0.0/{target}/rbac/group/role Generated from YANG model
      tags:
      - RbacV100targetRbacGroup
    parameters:
    - content:
        text/plain; charset=utf-8:
          schema:
            type: string
      description: key for role
      in: path
      name: roleid
      required: true
    - $ref: '#/components/parameters/target'
    post:
      operationId: postRbacV100targetRbacGroupRole
      responses:
        default:
          description: ""
      summary: POST Generated from YANG model
  /rbac/v1.0.0/{target}/rbac/role/{roleid}:
    delete:
      operationId: deleteRbacV100targetRbacRole
      responses:
        default:
          description: ""
      summary: DELETE Generated from YANG model
    get:
      operationId: getRbacV100targetRbacRole
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RbacV100targetRbacRole'
          description: GET OK 200
      summary: GET /rbac/v1.0.0/{target}/rbac/role Generated from YANG model
      tags:
      - RbacV100targetRbac
    parameters:
    - content:
        text/plain; charset=utf-8:
          schema:
            type: string
      description: key for role
      in: path
      name: roleid
      required: true
    - $ref: '#/components/parameters/target'
    post:
      operationId: postRbacV100targetRbacRole
      responses:
        default:
          description: ""
      summary: POST Generated from YANG model
  /rbac/v1.0.0/{target}/rbac/role/permission:
    delete:
      operationId: deleteRbacV100targetRbacRolePermission
      responses:
        default:
          description: ""
      summary: DELETE Generated from YANG model
    get:
      operationId: getRbacV100targetRbacRolePermission
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RbacV100targetRbacRolePermission'
          description: GET OK 200
      summary: GET /rbac/v1.0.0/{target}/rbac/role/permission Generated from YANG model
      tags:
      - RbacV100targetRbacRole
    parameters:
    - $ref: '#/components/parameters/target'
    post:
      operationId: postRbacV100targetRbacRolePermission
      responses:
        default:
          description: ""
      summary: POST Generated from YANG model
